// <auto-generated />
using System;
using MSLunchv1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSLunchv1.Data.Migrations
{
    [DbContext(typeof(MSLunchv1Context))]
    [Migration("20181211052332_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MSLunchv1.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Grade");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Notes")
                        .HasMaxLength(500);

                    b.Property<string>("SISID")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("TableID");

                    b.HasKey("ID");

                    b.HasIndex("TableID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("MSLunchv1.Models.Table", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TableCapacity");

                    b.Property<string>("TableDescription");

                    b.Property<int>("TableGrade");

                    b.Property<int>("TableNo");

                    b.HasKey("ID");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("MSLunchv1.Models.Student", b =>
                {
                    b.HasOne("MSLunchv1.Models.Table", "Table")
                        .WithMany("Students")
                        .HasForeignKey("TableID");
                });
#pragma warning restore 612, 618
        }
    }
}
